"""empty message

Revision ID: 562dcef92b8a
Revises: 69ce811e3268
Create Date: 2024-07-26 16:02:03.041922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '562dcef92b8a'
down_revision = '69ce811e3268'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actor', schema=None) as batch_op:
        batch_op.drop_column('img_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_url', sa.VARCHAR(length=200), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
