"""empty message

Revision ID: 69dda315a6cc
Revises: 3eaa73dd7a44
Create Date: 2024-07-17 13:10:52.952140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69dda315a6cc'
down_revision = '3eaa73dd7a44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('director')
        batch_op.drop_column('casting')
        batch_op.drop_column('genre_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('casting', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('director', sa.VARCHAR(length=300), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
